.gitignore, server.js
tested connection and it works
=> connects to mongo

client/package-lock.json, models/kindActs.js, models/userInfo.js, package-lock.json, package.json
Check it out lmk if you want me to add or change anything
=> created models

models/kindActs.js, models/userInfo.js, package-lock.json, package.json
=> updated models

client/src/App.js, client/src/Components/intro/index.js
=> updating intro compentent

models/userInfo.js, routes/api/index.js, routes/api/kindacts.js, routes/api/users.js, routes/index.js
adding routes for interacting with the db
=> creates routes

client/src/App.js, client/src/Components/badge/index.js, client/src/Components/intro/index.js, client/src/Components/team/index.js, client/src/context/KindActContext.js, client/src/index.js, package-lock.json, package.json
added context & router for pages
=> adds useContext & Router to app

client/src/pages/Acts/Acts.js, client/src/pages/Acts/index.js, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Dashboard/index.js
Adds folders for Dashboard & Acts pages
=> Adds pages folder with Dashboard and Acts pages

client/src/Components/intro/index.js
Fixes class name issue in intro component
=> Fixes class name issue in intro component

client/src/App.js, client/src/pages/Acts.js, client/src/pages/Dashboard/index.js, client/src/pages/Learn.js, client/src/pages/Learn/index.js
updated dashboard page to acts page
=> Adds updated acts page

client/src/App.js, client/src/Components/Chart/index.js, controller/UserController.js, models/kindActs.js
fixes bugs that merging chart caused
=> fixes chart

client/src/Components/AddBtn/index.js, client/src/Components/Chart/index.js, client/src/Components/Chart/style.css, client/src/pages/Dashboard/Dashboard.js, client/src/utils/API.js, controller/UserController.js
some styling for canvasjs component & addBtn functionality, not working yet
=> works on addBtn functionality

.vscode/settings.json, client/src/Components/SignIn/index.js, client/src/utils/API.js, controller/UserController.js, models/userInfo.js, routes/api/users.js
it's broken, but we're close...some redundancies may exist.
=> works on login routes & functionality

client/src/Components/AddBtn/index.js, client/src/Components/AddBtn/style.css, client/src/Components/DashBadge/index.js, client/src/Components/DashBadge/style.css, client/src/Components/Form/index.js, client/src/Components/Form/style.css, client/src/Components/List/index.js, client/src/Components/List/style.css, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Dashboard/style.css
=> Adds updated dashboard style

server.js
=> fixes merge

client/src/App.js, client/src/Components/Nav/style.css, client/src/Components/about/style.css, client/src/Components/badge/index.js, client/src/Components/badge/style.css, client/src/Components/intro/style.css, client/src/Components/team/index.js, client/src/Components/team/style.css
=> updating font styling and divs

client/src/Components/team/index.js
=> updating names

client/src/Components/team/index.js
=> updating pics

client/src/Components/AddBtn/style.css, client/src/Components/Form/index.js, client/src/Components/Form/style.css, client/src/Components/List/style.css, client/src/pages/Dashboard/Dashboard.js
Fixes styling issues on dashboard
=> Updates style of dashboard components

client/src/Components/about/index.js
=> updating about us branch, merge this one

client/src/Components/intro/style.css
fixes intro image so it doesnt overlap to next section
=> Fixes intro image

client/src/Components/MyDashBtn/index.js, client/src/Components/Nav/style.css, client/src/Components/SignIn/index.js, client/src/Components/SignIn/style.css, client/src/Components/SignOut/index.js, client/src/Components/SignOut/style.css, client/src/Components/SignUp/index.js, client/src/Components/SignUp/style.css
=> Updates styling of homepage

client/src/Components/Chart/index.js, client/src/pages/Dashboard/Dashboard.js, controller/UserController.js
=> Chart view4

.vscode/settings.json, client/src/pages/Dashboard/Dashboard.js, controller/KindActsController.js
makes date prettier with moment.js
=> updates display of date to DOM

client/src/Components/Chart/index.js, client/src/Components/SignUp/index.js, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Dashboard/style.css, controller/KindActsController.js, models/kindAct.js
=> fixes how dates should be sorted in the various lists & charts

client/src/Components/Chart/index.js, client/src/Components/Chart/style.css, client/src/Components/DashBadge/style.css, client/src/Components/Form/style.css, client/src/Components/KyndList/style.css, client/src/Components/List/style.css, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Dashboard/style.css, scripts/seedsDB.js
should be the finalized version of the dash. Also added some styling to the chart component
=> Updates dashboard styling

client/src/Components/Chart/style.css, client/src/Components/KyndList/style.css, client/src/Components/List/style.css, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Dashboard/style.css
=> Adds final styling to dashboard

client/src/Components/Nav/index.js, client/src/context/UserPointsContext.js, client/src/pages/Dashboard/Dashboard.js
Adds initial code to have user points show on nav when logged in
=> Adds user points

client/src/App.js
=> Adds user points context to app.js file

client/src/App.js, client/src/context/UserPointsContext.js, client/src/pages/Dashboard/Dashboard.js, client/src/utils/API.js
functionality to update users points
=> Adds functionality to update users points

client/src/Components/Nav/index.js
=> username shows again in nav

client/src/Components/Nav/index.js, models/userInfo.js
=> updates user point display if new user

client/src/pages/Dashboard/Dashboard.js
=> updates user pt display on dashboard page
